name: Atualizar JSON de Notícias

on:
  schedule:
    - cron: '0 7 * * *'  # Todos os dias às 07:00 UTC (04:00 no Brasil)
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: pip install beautifulsoup4 requests

    - name: Executar script para gerar JSON
      run: python gerar_noticias_com_imagem.py

    - name: Commit e Push se houve mudanças
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add noticias.json
        git commit -m "Atualização diária do JSON de notícias" || echo "Sem alterações"
        git push
